name: Build and Deploy to EKS

on:
  push:
    branches:
      - main   # Trigger workflow on pushes to the main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the code
      uses: actions/checkout@v2

    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        distribution: 'temurin'  # Specify Java distribution
        java-version: '17'

    - name: Build with Maven
      run: mvn clean install -DskipTests   # Skip tests since no database is used
      working-directory: ./automation       # Set working directory to /automation

    - name: Build Docker image
      run: docker build -t shahnawaz312/java-app:latest .
      working-directory: ./automation       # Set working directory to /automation

    - name: Login to DockerHub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Push Docker image to DockerHub
      run: docker push shahnawaz312/java-app:latest

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Update kubeconfig to access EKS cluster
      run: aws eks update-kubeconfig --name eksdemo

    # - name: Deploy MySQL to Kubernetes
    #   run: |
    #     kubectl apply -f mysql-deployment.yaml
    #     kubectl apply -f mysql-service.yaml

    # - name: Wait for MySQL to be ready
    #   run: |
    #     for i in {1..30}; do
    #       if kubectl get pods | grep mysql | grep Running; then
    #         echo "MySQL is ready!"
    #         break
    #       fi
    #       echo "Waiting for MySQL..."
    #       sleep 10
    #     done

    - name: Deploy the application
      run: |
        kubectl apply -f ./automation/deployment.yml
        kubectl apply -f ./automation/service.yml

    - name: Wait for 10 seconds
      run: sleep 10
 
    - name: Verify Deployment
      run: kubectl get all 

      
